<!--@subject {{var subject}} @-->
<!--@vars
{"store url=\"\"":"Store Url",
"skin url=\"images/logo_email.gif\" _area='frontend'":"Email Logo Image"}
@-->
<!--@styles
body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
@-->
{{template config_path="design/email/header_template"}}

<table cellpadding="0" cellspacing="0" border="0" align="center" style="background-color: #FAFAFA; width: 100%;">
	<tr>
		<td class="action-content">
			<h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">Dear {{var firstName}} {{var lastName}}, thank you for your purchase.</h3>
			<h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">Please follow this link to complete your purchase: <a href="{{var url}}">{{var url}}</a> </h3>
			<h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; "> Your cart items: </h3>
				{{block class='Magento\\Framework\\View\\Element\\Template' area='frontend' template='Bread_BreadCheckout::breadcheckout/checkout_items.phtml' items=$items}}
			<br/>

		</td>
	</tr>
</table>

{{template config_path="design/email/footer_template"}}