<?php
/**
 * @var \Magento\Backend\Block\Template $this
 */
?>
<style>
    .bread-logo {
        width: 133px;
        height: 44px;
        display: block;
        background: url('<?php echo $this->getViewFileUrl('Bread_BreadCheckout/bread/images/bread-logo.png'); ?>') 0px 0 no-repeat;
    }

    .bread-brand {
        color: #fff;
        background-color: #0c5a7b;
        border: 1px solid #ddd;
        padding: 10px;
        font-size: 125%;
    }
</style>
