<?php
/**
 * @var $block Magento\Checkout\Block\Cart
 * @var $viewModel Bread\BreadCheckout\ViewModel\Cart\CartView
 */
$viewModel = $block->getData('view_model');
if(!$viewModel->isAllowedRender($block->getQuote())){
    return;
}
?>
<?= /* @noEscape */ $block->getBeforeHtml(); ?>
<div id="bread-btn-cntnr">
    <div id="bread-checkout-btn" title="Bread Checkout" class="button" <?= /* @noEscape */ $viewModel->getIsDefaultSize(); ?>>
        <span>
            <span><?= /* @noEscape */ __('Bread Checkout'); ?></span>
        </span>
    </div>
    <div class="button-prevent" id="button-prevent">
        <span class="buy_error_tip override_tip" data-content="<?= /* @noEscape */ $block->escapeHtml($viewModel->productTypeErrorMessage()) ?>">&nbsp;</span>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/validate', 'mage/validation'], function($, quote) {

        var validateProductTypes = Boolean(<?= /* @noEscape */ $viewModel->validateAllowedProductTypes() ?>);
        if (validateProductTypes === false) {
            var buttonPrevent = $('#button-prevent');
            buttonPrevent.css('width','100%');
            buttonPrevent.css('height','100%');
            buttonPrevent.show();
        }

        document.configureButton = function(items) {
            var address             = <?= /* @noEscape */ $viewModel->customerHelper->getShippingAddressData(); ?>;
            var billingAddress      = <?= /* @noEscape */ $viewModel->customerHelper->getBillingAddressData(); ?>;
            var buttonOnProduct     = <?= /* @noEscape */ $viewModel->catalogHelper->isButtonOnProducts(); ?>;
            var buttonCss           = '<?= /* @noEscape */ $viewModel->getButtonDesign(); ?>';
            var financingInfo       = <?= /* @noEscape */ $viewModel->serializer->serialize($viewModel->catalogHelper->getFinancingData()); ?>;
            var total = 0;
            for (var i = 0; i < items.length; i++) {
                total += items[i]['price'] * items[i]['quantity'];
            }

            var breadConfig = {
                buttonId: "bread-checkout-btn",
                asLowAs: Boolean(<?= /* @noEscape */ $viewModel->catalogHelper->isAsLowAs(); ?>),
                actAsLabel: false,
                <?php if (!$viewModel->dataHelper->isHealthcare()) : ?>
                items: items,
                <?php else : ?>
                customTotal: total,
                <?php endif; ?>
                allowCheckout: <?= /* @noEscape */ $viewModel->getAllowCheckout(); ?>,
                buttonLocation: '<?= /* @noEscape */ \Bread\BreadCheckout\Helper\Data::BUTTON_LOCATION_CART_SUMMARY; ?>',

                done: function (err, tx_token) {
                    if (tx_token !== undefined) {
                        var i = document.createElement('input');
                        var k = document.createElement('input');
                        i.type = 'hidden';
                        i.name = 'token';
                        i.value = tx_token;
                        k.type = 'hidden';
                        k.name = 'form_key';
                        k.value = $.cookie('form_key');
                        var f = document.createElement('form');
                        f.action = '<?= /* @noEscape */ $viewModel->getValidateOrderUrl(); ?>';
                        f.method = 'POST';
                        f.appendChild(i);
                        f.appendChild(k);
                        document.body.appendChild(f);
                        f.submit();
                    } else {
                        var errorInfo = {
                            bread_config: breadConfig,
                            err: err
                        };
                        document.logBreadIssue('error', errorInfo, 'tx_token undefined in done callback');
                    }
                },

                /**
                 * Calculate tax value callback
                 *
                 * @param shippingAddress
                 * @param callback
                 */
                calculateTax: function (shippingAddress, callback) {
                    shippingAddress.block_key        = '<?= /* @noEscape */ \Bread\BreadCheckout\Helper\Data::BLOCK_CODE_CHECKOUT_OVERVIEW; ?>';
                    shippingAddress.additional_data  = <?= /* @noEscape */  $viewModel->serializer->serialize($block->setAdditionalData()); ?>;

                    var taxEstimationUrl = '<?= /* @noEscape */ $viewModel->catalogHelper->getTaxEstimateUrl(); ?>';
                    var shippingString = JSON.stringify(shippingAddress);
                    var errorInfo;

                    $.ajax({
                        url: taxEstimationUrl,
                        data: { shippingInfo: shippingString },
                        type: 'post'
                    }).done(function (response) {
                        try {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingString,
                            };
                            if (response !== null && typeof response === 'object') {
                                if (response.error) {
                                    document.logBreadIssue('error', errorInfo, 'Error estimating tax');
                                    alert(response.message);
                                } else {
                                    callback(null, response.result);
                                }
                            } else {
                                document.logBreadIssue('error', errorInfo, 'Response from ' + taxEstimationUrl + ' was not of type Object');
                            }
                        }
                        catch (e) {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingString,
                            };
                            document.logBreadIssue('error', errorInfo, e);
                        }
                    }).fail(function(error) {
                        errorInfo = {
                            shipping_info: shippingString,
                        };
                        document.logBreadIssue('error', errorInfo,
                            'Error code returned when calling ' + taxEstimationUrl + ', with status: ' + error.statusText);
                    });
                },

                /**
                 * Calculate shipping cost callback
                 *
                 * @param shippingAddress
                 * @param callback
                 */
                calculateShipping: function (shippingAddress, callback) {
                    shippingAddress.block_key        = '<?= /* @noEscape */  \Bread\BreadCheckout\Helper\Data::BLOCK_CODE_CHECKOUT_OVERVIEW; ?>';
                    shippingAddress.additional_data  = <?= /* @noEscape */ $viewModel->serializer->serialize($block->setAdditionalData()); ?>;

                    var shippingAddressEstimationUrl = '<?= /* @noEscape */ $viewModel->catalogHelper->getShippingEstimateUrl(); ?>';
                    var errorInfo;

                    $.ajax({
                        url: shippingAddressEstimationUrl,
                        data: shippingAddress,
                        type: 'post'
                    }).done(function (response) {
                        try {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingAddress,
                            };
                            if (response !== null && typeof response === 'object') {
                                if (response.error) {
                                    document.logBreadIssue('error', errorInfo, 'Error calculating shipping');
                                    alert(response.message);
                                } else {
                                    callback(null, response.result);
                                }
                            } else {
                                document.logBreadIssue('error', errorInfo, 'Response from ' + shippingAddressEstimationUrl + ' was not of type Object');
                            }
                        }
                        catch (e) {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingAddress,
                            };
                            document.logBreadIssue('error', errorInfo, e);
                        }
                    }).fail(function(error) {
                        errorInfo = {
                            shipping_info: shippingAddress,
                        };
                        document.logBreadIssue('error', errorInfo,
                            'Error code returned when calling ' + shippingAddressEstimationUrl + ', with status: ' + error.statusText);
                    });
                }
            };

            if (buttonCss !== null && buttonCss !== '' && buttonCss != false) {
                breadConfig.customCSS = buttonCss;
            }

            if (address !== false) {
                breadConfig.shippingContact = address;
            }

            if (billingAddress !== false) {
                breadConfig.billingContact = billingAddress;
            }

            if (buttonOnProduct === true) {
                breadConfig.actAsLabel = false;
            }

            var targetedFinancingStatus = <?= /* @noEscape */ $viewModel->getTargetedFinancingStatusJson(); ?>;

            if (targetedFinancingStatus.shouldUseFinancingId) {
                breadConfig.financingProgramId = targetedFinancingStatus.id;
            }

            var discountAmount =- document.round(window.checkoutConfig.totalsData.discount_amount);
            if (discountAmount > 0) {
                breadConfig.discounts = [{
                    amount: discountAmount,
                    description: (window.checkoutConfig.totalsData.coupon_code !== null) ?
                        window.checkoutConfig.totalsData.coupon_code :
                        "Discount"
                }];
            }

            if (typeof bread !== 'undefined') {
                bread.checkout(breadConfig);
            }
        };

        document.round = function(value) {
            return parseInt(Math.round(value * 100));
        };

        $(document).ready(function() {
            document.defaultItems       = <?= /* @noEscape */ $viewModel->getProductDataJson(); ?>;
            document.previousPrice      = document.defaultItems[0]["price"];
            document.previousSku        = document.defaultItems[0]["sku"];
            document.configureButton(document.defaultItems);
        });
    });
</script>
