<table style="width: 100%;text-align: left;">
    <tr><th style="width:110px;"></th><th>Name</th><th style="width:20%;">SKU</th><th style="width:10%;">Quantity</th><th style="width:15%;">Price</th></tr>
    <?php foreach ($this->getItems() as $item) : ?>
        <tr>
            <td> <img src="<?= /* @noEscape */ $item["imageUrl"];?>" width="100"/> </td>
            <td> <?= /* @noEscape */ $item["name"];?> </td>
            <td> <?= /* @noEscape */ $item["sku"];?> </td>
            <td> <?= /* @noEscape */ $item["quantity"];?> </td>
            <td> <?= /* @noEscape */ $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($item["price"] / 100, true, false); ?> </td>
        </tr>
    <?php endforeach;?>
</table>