<?php /** @var \Bread\BreadCheckout\Block\Product\Category $block */ ?>

<?php
$product   = $block->getProduct();
$productId = $product->getId();
?>
<div id="bread-btn-cntnr-<?= /* @noEscape */ $productId; ?>">
    <div id='bread-checkout-btn-<?= /* @noEscape */ $productId; ?>' title="Bread Checkout"
         class="button" <?= /* @noEscape */ $block->useDefaultButtonSizeCategory(); ?>>
        <span>
            <span><?= /* @noEscape */ __('Bread Checkout'); ?></span>
        </span>
    </div>
    <div class='button-prevent'
         id='button-prevent'>
        <span class="buy_error_tip override_tip" data-content="<?= /* @noEscape */ __('Please complete product configuration') ?>">&nbsp;</span>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        document.configureButton<?= /* @noEscape */ $productId;?> = function (items) {
            var address = <?= /* @noEscape */ $block->getShippingAddressData(); ?>;
            var billingAddress = <?= /* @noEscape */ $block->getBillingAddressData(); ?>;
            var labelOnly = <?= /* @noEscape */ $block->isLabelOnlyOnCategories(); ?>;
            var buttonCss = '<?= /* @noEscape */ $block->getCATButtonDesign(); ?>';
            var financingInfo = <?= /* @noEscape */ $block->getFinancingJson(); ?>;

            var breadConfig = {
                buttonId: 'bread-checkout-btn-<?= /* @noEscape */ $productId;?>',
                asLowAs: <?= /* @noEscape */ $block->isAsLowAsCAT(); ?>,
                showInWindow: <?= /* @noEscape */ $block->getShowInWindowCAT()?>,
                <?php if (!$block->isHealthcare()) : ?>
                items: items,
                <?php else : ?>
                customTotal: items[0]['price'],
                <?php endif; ?>
                discounts: [],
                allowCheckout: false,
                buttonLocation: '<?= /* @noEscape */ $block->getCategoryPageLocation(); ?>',
                done: function (err, tx_token) {
                    if (tx_token !== undefined) {
                        var i = document.createElement('input');
                        i.type = 'hidden';
                        i.name = 'token';
                        i.value = tx_token;
                        var f = document.createElement('form');
                        f.action = '<?= /* @noEscape */ $block->getValidateOrderURL(); ?>';
                        f.method = 'POST';
                        f.appendChild(i);
                        document.body.appendChild(f);
                        f.submit();
                    } else {
                        var errorInfo = {
                            bread_config: breadConfig,
                            err: err
                        };
                        document.logBreadIssue('error', errorInfo, 'tx_token undefined in done callback');
                    }
                },

            };

            if (buttonCss !== null && buttonCss !== '' && buttonCss != false) {
                breadConfig.customCSS = buttonCss;
            }
            <?php if (!$block->isHealthcare()) : ?>
            if (address !== false) {
                breadConfig.shippingContact = address;
            }

            if (billingAddress !== false) {
                breadConfig.billingContact = billingAddress;
            }
            <?php endif; ?>
            if (!labelOnly) {
                breadConfig.actAsLabel = false;
            }

            if(financingInfo.enabled && financingInfo.mode.cart){
                var cartSizeFinancingId = financingInfo.id;
                var cartSizeThreshold = financingInfo.threshold;
                var itemsPriceSum = items.reduce(function(sum, item) { return sum + item.price * item.quantity; }, 0) / 100;
                breadConfig.financingProgramId = (itemsPriceSum >= cartSizeThreshold) ? cartSizeFinancingId : 'null';
            } else if (financingInfo.enabled && financingInfo.mode.sku){
                var productSku = "<?= $block->getProduct()->getSku(); ?>";
                if(financingInfo.sku_limit.includes(productSku) === true){
                    breadConfig.financingProgramId = financingInfo.id;
                }
            }

            if (typeof bread !== 'undefined') {
                bread.checkout(breadConfig);
            }
        };

        $(document).ready(function () {
            <?php
            $data = $block->getProductDataJson($product);
            ?>
            var product = <?= /* @noEscape */ $data; ?>;
            var originalPrice = product.price;

            document.configureButton<?= /* @noEscape */ $productId; ?>([product]);
            $("[data-role=priceBox][data-product-id=<?= /* @noEscape */ $productId;?>]").on("updatePrice", function (event, data) {
                if (data) {
                    product.price = Math.round(originalPrice + data.prices.finalPrice.amount * 100);
                    document.configureButton<?= /* @noEscape */ $productId; ?>([product]);
                }
            });

        });
    });

</script>