<?php /** @var Bread\BreadCheckout\Block\Checkout\Overview $block */ ?>
<?php  echo $block->getBeforeHtml(); ?>
<div id="bread-btn-cntnr-minicart">
    <div id="bread-checkout-btn-minicart" title="Bread Checkout" class="button" <?php /* @noEscape */ echo $block->getIsDefaultSize(); ?>>
        <span>
            <span><?php /* @noEscape */ echo __('Bread Checkout'); ?></span>
        </span>
    </div>
    <div class="button-prevent" id="button-prevent">
        <span class="buy_error_tip override_tip" data-content="<?= $block->productTypeErrorMessage() ?>">&nbsp;</span>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/validate', 'mage/validation'], function($){

        var validateProductTypes = Boolean(<?= $block->validateAllowedProductTypes() ?>);
        if(validateProductTypes === false){
            var buttonPrevent = $('#button-prevent');
            buttonPrevent.css('width','100%');
            buttonPrevent.css('height','100%');
            buttonPrevent.show();
        }

        document.configureButton = function (items) {
            var address             = <?php /* @noEscape */ echo $block->getShippingAddressData(); ?>;
            var billingAddress      = <?php /* @noEscape */ echo $block->getBillingAddressData(); ?>;
            var buttonOnProduct     = <?php /* @noEscape */ echo $block->getIsButtonOnProduct(); ?>;
            var buttonCss           = '<?php /* @noEscape */ echo $block->getButtonDesign(); ?>';
            var cartSizeFinancing   = <?php /* @noEscape */ echo $block->getCartSizeFinancingJson(); ?>;
            var total = 0;
            for(var i = 0; i < items.length; i++){
                total += items[i]['price'] * items[i]['quantity'];
            }

            var breadConfig = {
                buttonId: "bread-checkout-btn-minicart",
                asLowAs: <?php /* @noEscape */ echo $block->getAsLowAs(); ?>,
                actAsLabel: false,
                <?php if (!$this->isHealthcare()) : ?>
                items: items,
                <?php else : ?>
                customTotal: total,
                <?php endif; ?>
                allowCheckout: <?php /* @noEscape */ echo $this->getAllowCheckout(); ?>,
                buttonLocation: '<?php /* @noEscape */ echo $this->getCartSummaryLocation(); ?>',

                done: function (err, tx_token) {
                    if (tx_token !== undefined) {
                        var i = document.createElement('input');
                        var k = document.createElement('input');
                        i.type = 'hidden';
                        i.name = 'token';
                        i.value = tx_token;
                        k.type = 'hidden';
                        k.name = 'form_key';
                        k.value = $.cookie('form_key');
                        var f = document.createElement('form');
                        f.action = '<?php /* @noEscape */ echo $block->getValidateOrderUrl(); ?>';
                        f.method = 'POST';
                        f.appendChild(i);
                        f.appendChild(k);
                        document.body.appendChild(f);
                        f.submit();
                    } else {
                        var errorInfo = {
                            bread_config: breadConfig,
                            err: err
                        };
                        document.logIssue('error', errorInfo, 'tx_token undefined in done callback');
                    }

                    return;
                },

                /**
                 * Calculate tax value callback
                 *
                 * @param shippingAddress
                 * @param callback
                 */
                calculateTax: function (shippingAddress, callback) {
                    shippingAddress.block_key        = '<?php /* @noEscape */ echo $block->getBlockCode(); ?>';
                    shippingAddress.additional_data  = <?php /* @noEscape */ echo  $block->jsonEncode($block->setAdditionalData()); ?>;

                    var taxEstimationUrl = '<?php /* @noEscape */ echo $block->getTaxEstimationUrl(); ?>';
                    var shippingString = JSON.stringify(shippingAddress);
                    var errorInfo;

                    $.ajax({
                        url: taxEstimationUrl,
                        data: { shippingInfo: shippingString },
                        type: 'post'
                    }).done(function (response) {
                        try {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingString,
                            };
                            if (typeof response == 'object') {
                                if (response.error) {
                                    document.logIssue('error', errorInfo, 'Error estimating tax');
                                    alert(response.message);
                                } else {
                                    callback(null, response.result);
                                }
                            } else {
                                document.logIssue('error', errorInfo, 'Response from ' + taxEstimationUrl + ' was not of type Object');
                            }
                        }
                        catch (e) {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingString,
                            };
                            document.logIssue('error', errorInfo, e);
                        }
                    }).fail(function(error) {
                        errorInfo = {
                            shipping_info: shippingString,
                        };
                        document.logIssue('error', errorInfo,
                            'Error code returned when calling ' + taxEstimationUrl + ', with status: ' + error.statusText);
                    });
                },

                /**
                 * Calculate shipping cost callback
                 *
                 * @param shippingAddress
                 * @param callback
                 */
                calculateShipping: function (shippingAddress, callback) {
                    shippingAddress.block_key        = '<?php /* @noEscape */ echo $block->getBlockCode(); ?>';
                    shippingAddress.additional_data  = <?php /* @noEscape */ echo  $block->jsonEncode($block->setAdditionalData()); ?>;

                    var shippingAddressEstimationUrl = '<?php /* @noEscape */ echo $block->getShippingAddressEstimationUrl(); ?>';
                    var errorInfo;

                    $.ajax({
                        url: shippingAddressEstimationUrl,
                        data: shippingAddress,
                        type: 'post'
                    }).done(function (response) {
                        try {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingAddress,
                            };
                            if (typeof response == 'object') {
                                if (response.error) {
                                    document.logIssue('error', errorInfo, 'Error calculating shipping');
                                    alert(response.message);
                                } else {
                                    callback(null, response.result);
                                }
                            } else {
                                document.logIssue('error', errorInfo, 'Response from ' + shippingAddressEstimationUrl + ' was not of type Object');
                            }
                        }
                        catch (e) {
                            errorInfo = {
                                response: response,
                                shipping_info: shippingAddress,
                            };
                            document.logIssue('error', errorInfo, e);
                        }
                    }).fail(function(error) {
                        errorInfo = {
                            shipping_info: shippingAddress,
                        };
                        document.logIssue('error', errorInfo,
                            'Error code returned when calling ' + shippingAddressEstimationUrl + ', with status: ' + error.statusText);
                    });
                }
            };

            if (buttonCss !== null && buttonCss !== '' && buttonCss != false) {
                breadConfig.customCSS = buttonCss;
            }

            if (address !== false) {
                breadConfig.shippingContact = address;
            }

            if (billingAddress !== false) {
                breadConfig.billingContact = billingAddress;
            }

            if (buttonOnProduct === true) {
                breadConfig.actAsLabel = false;
            }

            if(cartSizeFinancing.enabled){
                var cartSizeFinancingId = cartSizeFinancing.id;
                var cartSizeThreshold = cartSizeFinancing.threshold;
                var items = document.minicartItems;
                var itemsPriceSum = items.reduce(function(sum, item) {return sum + item.price * item.quantity}, 0) / 100;
                breadConfig.financingProgramId = (itemsPriceSum >= cartSizeThreshold) ? cartSizeFinancingId : 'null';
            }

            var discountAmount = <?= json_encode($this->quoteHelper->getDiscountData());?>;
            if (discountAmount.length > 0) {
                breadConfig.discounts = [{
                    amount: discountAmount[0].amount,
                    description: (discountAmount[0].description !== null) ?
                        discountAmount[0].description :
                        "Discount"
                }];
            }
            if (typeof bread !== 'undefined') {
                bread.checkout(breadConfig);
            }
        };

        document.round = function(value) {
            return parseInt(Math.round(value * 100));
        };

        $(document).ready(function() {
            var minicartItems       = <?php /* @noEscape */ echo $block->getProductDataJson(); ?>;
            document.configureButton(minicartItems);
        });
    });
</script>
