<?php
/**
 * @var $block Magento\Catalog\Block\Product\View\Options
 * @var $viewModel Bread\BreadCheckout\ViewModel\Product\Options
 * @var $product Magento\Catalog\Model\Product
 */
$viewModel = $block->getData('view_model');
$product = $block->getProduct();

if (!$viewModel->isAllowedRender($product)) {
    return;
}
?>
<?php $_options = $block->decorateArray($product->getOptions()); ?>
<?php if (!empty($_options)) : ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Bread_BreadCheckout/js/product/options": {
                    "optionsData": <?= /* @noEscape */ $viewModel->getCustomOptionsData($_options); ?>,
                    "productType": "<?= /* @noEscape */ $product->getTypeId()?>"
                }
            }
        }
    </script>
<?php endif; ?>
