<?php /** @var $block Bread\BreadCheckout\Block\Product\View */ ?>
<?= /* @noEscape */ $block->getBeforeHtml(); ?>

<div class="splitpay-clickable-price" style="padding-bottom: 5px"></div>

<script type="text/javascript">
    require(['jquery', 'Bread_BreadCheckout/js/product/splitpay'], function($, splitpay) {

        document.splitpayconfigureButton = function (items) {
            var buttonCss           = '<?= /* @noEscape */ $block->getButtonDesign(); ?>';
            var financingInfo   = <?= /* @noEscape */ $block->getFinancingJson(); ?>;
            var breadConfig = {
                <?php if (!$block->isHealthcare()) : ?>
                items: items,
                <?php else : ?>
                customTotal: items[0]['price'],
                <?php endif; ?>
                discounts: <?= /* @noEscape */ $block->getDiscountDataJson(); ?>,
                allowCheckout: false,
                done: function() {},

                /**
                 * Add to cart call back used when allow checkout from product page = false
                 *
                 * @param callback
                 */
                addToCart:  function(callback) {
                    document.getElementById('product_addtocart_form').submit();
                }
            };

            if (buttonCss !== null && buttonCss !== '' && buttonCss != false) {
                breadConfig.customCSS = buttonCss;
            }

            if(financingInfo.enabled && financingInfo.mode.cart){
                var cartSizeFinancingId = financingInfo.id;
                var cartSizeThreshold = financingInfo.threshold;
                var itemsPriceSum = items.reduce(function(sum, item) { return sum + item.price * item.quantity; }, 0) / 100;
                breadConfig.financingProgramId = (itemsPriceSum >= cartSizeThreshold) ? cartSizeFinancingId : 'null';
            } else if (financingInfo.enabled && financingInfo.mode.sku){
                var productSku = "<?= /* @noEscape */ $block->getProduct()->getSku(); ?>";
                if(financingInfo.sku_limit.includes(productSku) === true){
                    breadConfig.financingProgramId = financingInfo.id;
                }
            }

            if (!document.splitpayhasCheckedConfigData) {

                var configDataUrl = '<?= /* @noEscape */ $block->getConfigDataUrl(); ?>';
                $.ajax({
                    url: configDataUrl,
                    type: 'post',
                    context: this
                }).done(function(data) {
                    document.splitpayhasCheckedConfigData = true;

                    if (data.shippingContact !== false) {
                        breadConfig.shippingContact = data.shippingContact;
                    }

                    if (data.billingContact !== false) {
                        breadConfig.billingContact = data.billingContact;
                    }

                    if (typeof bread !== 'undefined') {
                        splitpay.setupSplitpay(breadConfig, '.splitpay-clickable-price', true);
                    }
                }).fail(function(error) {
                    document.logBreadIssue('error', {},
                        'Error code returned when calling ' + configDataUrl + ', with status: ' + error.statusText);
                });

            } else {
                if (typeof bread !== 'undefined') {
                    splitpay.setupSplitpay(breadConfig, '.splitpay-clickable-price', true);
                }
            }

        };

        <?php if ($block->getProduct() != null) : ?>

        /**
         * Reconfigure Bread checkout button with updated
         * price and sku values
         */
        document.splitpayresetPriceAndSku = function(configurable) {
            if (!configurable) {
                document.splitpayconfigureButton(document.splitpaydefaultItems);
            }
            else {
                var price = document.splitpaycalculatePrice();

                if(typeof document.customOptions !== "undefined"){
                    sku = document.splitpayselectedSku + document.customOptions;
                } else {
                    sku = document.splitpayselectedSku;
                }

                if (sku != document.splitpaypreviousSku || price != document.splitpaypreviousPrice) {
                    document.splitpaypreviousSku                    = sku;
                    document.splitpaypreviousPrice                  = price;
                    document.splitpaydefaultItems[0]["sku"]         = document.splitpaypreviousSku;
                    document.splitpaydefaultItems[0]["price"]       = document.splitpaypreviousPrice;
                    document.splitpayconfigureButton(document.splitpaydefaultItems);
                }
            }
        };

        /**
         * Calculate updated price based on attribute selections
         * and/or custom options
         *
         * @returns int
         */
        document.splitpaycalculatePrice = function() {
            var price = 0;
            var customPrice = 0;

            if (document.priceWithOptions) {
                customPrice = document.priceWithOptions;
            }

            var selectedProductPrices = spConfig && spConfig.optionPrices[document.splitpayselectedSimpleProductId];

            if (selectedProductPrices) {
                price = parseInt(Math.round(selectedProductPrices.finalPrice.amount * 100));
            }

            return Math.max(price, customPrice);
        };
        <?php endif; ?>
        document.splitpaydefaultItems       = <?= /* @noEscape */ $block->getProductDataJson(); ?>;
        document.splitpaypreviousPrice      = document.splitpaydefaultItems[0]["price"];
        document.splitpaypreviousSku        = document.splitpaydefaultItems[0]["sku"];

        $(document).ready(function () {
            <?php if ($block->getProduct() != null) : ?>
            document.splitpayproductId                      = '<?= /* @noEscape */ $block->getProduct()->getId(); ?>';
            document.splitpaybaseProductSku                 = '<?= /* @noEscape */ $block->getProduct()->getSku(); ?>';
            document.splitpayselectedSku                    = '<?= /* @noEscape */ $block->getProduct()->getSku(); ?>';
            document.splitpayselectedSimpleProductId        = '<?= /* @noEscape */ $block->getProduct()->getId(); ?>';
            document.splitpayresetPriceAndSku(false);
            <?php else : ?>
            document.splitpayconfigureButton(document.splitpaydefaultItems);
            <?php endif; ?>
        });
    });
</script>
