<!--@subject Email Subject @-->
<!--@vars
{"store url=\"\"":"Store Url",
"skin url=\"images/logo_email.gif\" _area='frontend'":"Email Logo Image"}
@-->
<!--@styles
body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
@-->
{{template config_path="design/email/header_template"}}
<table cellpadding="0" cellspacing="0" border="0" align="center" style="background-color: #FAFAFA; width: 100%;">
    <tr>
        <td class="action-content">
            <h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">There was an error in processing your cart</h3>
            {{if token}}<h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">Transaction id: {{var token}}</h3>{{/if}}
            <h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">Error: {{var exception_message}}</h3>
            <h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">Server returned:</h3>
            <h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; ">{{var response}}</h3>
            <h3 style="font-weight: 400; font-family:'Open Sans', sans-serif; "></h3>
            <br/>

        </td>
    </tr>
</table>

{{template config_path="design/email/footer_template"}}