<table style="width: 100%;text-align: left;">
    <tr><th style="width:110px;"></th><th>Name</th><th style="width:20%;">SKU</th><th style="width:10%;">Quantity</th><th style="width:15%;">Price</th></tr>
    <?php foreach ($this->getItems() as $item):?>
        <?php
        ?>
        <tr>
            <td> <img src="<?php echo $item["imageUrl"];?>" width="100"/> </td>
            <td> <?php echo $item["name"];?> </td>
            <td> <?php echo $item["sku"];?> </td>
            <td> <?php echo $item["quantity"];?> </td>
            <td> <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($item["price"] / 100,true,false); ?> </td>
        </tr>
    <?php endforeach;?>
</table>