<?php 

/**
 * Fetch the Bread API version and payment info below
 */

use \Bread\BreadCheckout\Model\Ui\ConfigProvider;

$payment = $block->getOrder()->getPayment();
$method = $payment->getMethodInstance()->getCode();
$version = $payment->getData('bread_api_version');
if($version === 'bread_2') {
    $version = 'platform';
}
?>

<?php if($method == ConfigProvider::CODE && $version != "") : ?>
<div class="admin__page-section-item-content">
    <hr>
    <strong><?php echo __('Bread gateway version: ') ?></strong>
    <span class="price"><?= $version; ?></span>                        
</div>
<?php endif; ?>