<?php
/**
 * @var \Magento\Backend\Block\Template $this
 */
?>
<style>
    .bread-logo {
        width: 133px;
        height: 44px;
        display: block;
        background: url('<?php /* @noEscape */
                echo $block->getViewFileUrl('Bread_BreadCheckout/bread/images/bread-logo.png'); ?>');
        background-repeat: no-repeat;
        background-size: 133px 44px;
    }

    .bread-brand {
        color: #fff;
        background-color: #0c5a7b;
        border: 1px solid #ddd;
        padding: 10px;
        font-size: 125%;
    }

    .admin__fieldset .bread-clearer{
        clear: both;
        height: 5px;
    }

    .admin__fieldset .bread-send-mail{
        float:left;
        margin-left: 5px;
        cursor: pointer;
    }

    .admin__fieldset .bread-send-mail img{
        height: 33px;
    }

    .admin__fieldset .bread-create-cart{
        float:left;
    }

</style>
