<?php
/**
 * @var \Magento\Backend\Block\Template $this
 */
?>
<style>
    .bread-logo {
        width: 155px;
        height: 44px;
        margin-bottom: 10px;
        display: block;
        background: url('<?= /* @noEscape */ $block->getViewFileUrl('Bread_BreadCheckout/bread/images/bread-financial.png'); ?>');
        background-repeat: no-repeat;
        background-size: 155px 44px;
    }

    .rbc-logo {
        width: 155px;
        height: 44px;
        margin-bottom: 10px;
        display: block;
        background: url('<?= /* @noEscape */ $block->getViewFileUrl('Bread_BreadCheckout/bread/images/rbcpayplan.png'); ?>');
        background-repeat: no-repeat;
        background-size: 155px 44px;
    }
    
    .admin__fieldset .bread-clearer{
        clear: both;
        height: 5px;
    }

    .admin__fieldset .bread-row{
        float:left;
        margin-left: 5px;
        cursor: pointer;
    }

    .admin__fieldset .bread-send-mail img,
    .admin__fieldset .bread-api-mail img
    {
        height: 33px;
    }

    .admin__fieldset .bread-create-cart{
        float:left;
    }

</style>
